name: Update Market

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-market:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Fetch USD/JPY data
        run: |
          CURRENT_MONTH=$(TZ=Asia/Tokyo date +%Y%m)
          PREVIOUS_MONTH=$(TZ=Asia/Tokyo date -d "1 month ago" +%Y%m)

          curl "https://www.stat-search.boj.or.jp/api/v1/getDataCode?format=json&lang=jp&db=FM08&code=FXERD04&startDate=${PREVIOUS_MONTH}&endDate=${CURRENT_MONTH}" \
            -o usd_jpy.json

          LAST_INDEX=$(jq '
          .RESULTSET[0].VALUES.VALUES
          | to_entries
          | map(select(.value != null))
          | last
          | .key
          ' usd_jpy.json)
          
          USDJPY=$(jq -r ".RESULTSET[0].VALUES.VALUES[$LAST_INDEX]" usd_jpy.json)
          
          USDJPY_DATE=$(jq -r ".RESULTSET[0].VALUES.SURVEY_DATES[$LAST_INDEX]" usd_jpy.json)
          
          echo "USD/JPY = $USDJPY" > market.txt
          echo "Updated: $USDJPY_DATE" >> market.txt

      - name: Commit market data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add market.txt
          git commit -m "Update market data" || echo "No changes to commit"
          git push
